version: '3'

services:
   consulserver01: 
      image: consul:1.10
      container_name: consulserver01
      hostname: consulserver01
      command: ['consul', 'agent', '-config-dir=/etc/consul.d']
      volumes:
        - ./servers/server01:/etc/consul.d
      ports:
        -  "8500:8500"
   consulserver02: 
     image: consul:1.10
     container_name: consulserver02
     hostname: consulserver02
     command: ['consul', 'agent', '-config-dir=/etc/consul.d']
     volumes:
       - ./servers/server02:/etc/consul.d
     depends_on:
      - consulserver01
   consulserver03: 
     image: consul:1.10
     container_name: consulserver03
     hostname: consulserver03
     command: ['consul', 'agent', '-config-dir=/etc/consul.d']
     volumes:
        - ./servers/server03:/etc/consul.d
     depends_on:
      - consulserver02
      - consulserver01
   consulclient01: 
     image: consul:1.10
     container_name: consulclient01
     hostname: consulclient01
     command: ['consul', 'agent', '-config-dir=/etc/consul.d']
     volumes: 
         - ./clients/consul01:/etc/consul.d
   consulclient02: 
     image: consul:1.10
     container_name: consulclient02
     hostname: consulclient02
     command: ['consul', 'agent', '-config-dir=/etc/consul.d']
     volumes: 
         - ./clients/consul02:/etc/consul.d
   nginx: 
      image: nginx:latest
      container_name: nginx
      ports: 
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/html:/usr/share/nginx/html:ro
   node:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    hostname: node
    ports:
      - "8081:8081"
    volumes:
      - ./node:/app